import csv

'''
This file takes in the CSVs generated by the add_new_fields.py function and prepares them for use in the decision tree.
'''

features =  ['ROB','RISP','middle_at_bat','end_inning','no_hitter',
              'shutout','perfect_game','variance','score_against',
              'score_for','strikeout_count','walk_count','hit_count','total_bases', 'pitch_number', 'paResult']

def prepare(filename):
    ''' 
    Takes in a specified filename and parses the data for use in decision tree. 
    '''
    output = []
    with open(filename, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            temp = {}
            label = None
            for key, value in row.iteritems():
                # If data point is one of the features, place in output dictionary
                if key in features:
                    temp[key] = value
                # If last pitch of game by pitcher (label)
                if key == 'last_pitch_game':
                    label = value
            output.append((temp, label))

    print "\nData Preparation Complete.\n"
    return output
